const V = new URL(import.meta.url).search;
const { blockHelp, VARIANTS } = await import('./blocks.js' + V);

/* Two documents.
 *
 *   guide()   - the visual reference. Everything the tool can do,
 *               shown as source and then as the result it produces.
 *               Opened in its own window by the Reference button, and
 *               loaded on a first visit.
 *   starter() - what the New button gives you. Deliberately almost
 *               empty; the reference is a click away.
 *
 * The block and colour lists are generated from blocks.js, so adding
 * either one documents itself with no second place to update.
 */

const B = String.fromCharCode(92);            // a single backslash
const F = String.fromCharCode(96).repeat(3);  // a code fence
const T = String.fromCharCode(96);            // one backtick, inline code
const APOS = String.fromCharCode(8217);       // a typographic apostrophe

/* Source, then the same source rendered. The point of the guide is
 * that you never have to imagine the result. */
function demo(...lines) {
  return [F, ...lines, F, '', ...lines].join('\n');
}

/* One row per block, generated from blocks.js, so a block added there
 * is listed here without a second place to update. The worked entries
 * further down are written by hand - the table says what exists, the
 * entries show what each one looks like. */
function blockIndex() {
  return [
    '| Block | Title | What it is for |',
    '|---|---|---|',
    ...blockHelp().map((b) =>
      '| ' + T + b.name + T + ' | ' + (b.takesTitle ? 'yes' : '-') + ' | ' + b.help + ' |'),
  ].join('\n');
}

/* One roll box per colour, labelled with its own name. */
function colourDemos() {
  return VARIANTS.filter((v) => v !== 'npc')
    .map((v) => ['::: roll.' + v, v.charAt(0).toUpperCase() + v.slice(1), ':::'].join('\n'))
    .join('\n\n');
}

/* One page that touches every themed token, for themes.html to render
 * side by side. Deliberately short and dense: a theme is judged on how
 * a heading sits against body copy, how a rule reads against the page,
 * and whether a boxed panel still separates from the ground - not on
 * how much text fits. The caller passes cols=1, and this has to fit a
 * single 6x9 page without spilling into a second column, so keep it
 * tight when adding to it.
 */
export function themeSample() {
  return [
    '# Deep Water',
    '',
    'Body copy sets the register of a theme more than any heading does.',
    'Read at size, against the page ground, with a [link](#) and some',
    T + 'inline code' + T + ' in it.',
    '',
    '## Second level',
    '',
    '### Third level, which takes the accent',
    '',
    '> A blockquote leans on the accent for its rule and the dim text',
    '> colour for its body.',
    '',
    '::: box A boxed callout',
    'Panel against page. These two sit close together on purpose, so',
    'this is where a greyscale ramp fails first.',
    ':::',
    '',
    '::: aside',
    'An aside is the accent doing structural work, not decorative.',
    ':::',
    '',
    '| Column | Reads against |',
    '|---|---|',
    '| Header row | the second panel tone |',
    '| Body row | the page ground |',
    '',
    '::: stat Marsh Revenant',
    'Health 5 | Soak 3 | Ferocity 4',
    'The stat line is what a GM scans mid-fight, so it has to stay',
    'legible in every theme and both palettes.',
    ':::',
    '',
    '::: roll.pc',
    'Roll boxes carry the variant colours',
    ':::',
    '',
  ].join('\n');
}

export function starter() {
  return [
    '# Title',
    '',
    'Start writing. Two columns by default. The Ground picker in the',
    'toolbar puts a background on the page your cursor is in, and the',
    'Reference button opens a guide to everything else the tool can do.',
    '',
  ].join('\n');
}

export function guide() {
  return [
    '# The Brewery',
    '',
    'Everything this tool can do, shown as the markdown that produces it',
    'and then as the result. Pages are two columns by default.',
    '',
    'This document uses what it describes: it numbers its own pages, and',
    'three of them carry a background. Look at the foot of this page.',
    '',
    B + 'folio',
    '',
    '## Six markers',
    '',
    'The whole syntax is six things.',
    '',
    F,
    B + 'page',
    B + 'page cols=1 bg=hex',
    '',
    B + 'folio',
    B + 'seed 4815',
    B + 'ground hex',
    '',
    B + 'column',
    '',
    '::: name A title',
    ':::',
    F,
    '',
    'The first starts a new page, as one column or with a background if',
    'you say so. The next three are settings for the whole document:',
    'number the pages, draw this file' + APOS + 's own backgrounds, and put a',
    'ground under every page. The fifth starts the next column. The last',
    'opens a block, and the bare colons close it.',
    '',
    B + 'page bg=hex',
    '',
    '# Pages',
    '',
    'This page is set to ' + T + 'bg=hex' + T + ', so it is showing you the ground',
    'while it explains it.',
    '',
    'A page break can carry options, including one written on the first',
    'line of the document. An option this tool does not know is ignored,',
    'so a file written for an older version of it still opens.',
    '',
    '**Add page breaks** lays the document out and inserts the breaks it',
    'needs. It only ever adds: a break you placed yourself keeps its place',
    'and its options.',
    '',
    '**Remove breaks** takes them all out, which is what you want after',
    'changing trim or theme, since breaks packed for one size leave',
    'half-empty pages in another. A break carrying options is not simply',
    'deleted - that page wanted a background, or a single column, and that',
    'decision is not the packer' + APOS + 's to lose. It leaves a note where it',
    'stood:',
    '',
    F,
    '<!-- brew:page bg=hexdrift -->',
    F,
    '',
    'The note draws nothing, so the document reads as though the break were',
    'gone. Add page breaks turns each one back into the break it came from',
    'before it lays anything out, so the background lands on the page that',
    'asked for it rather than wherever the packing happened to reach.',
    '',
    'Neither one touches a ' + T + B + 'page' + T + ' written inside a code fence, so a',
    'document explaining this tool does not eat its own examples.',
    '',
    B + 'page',
    '',
    '## When a block is taller than the page',
    '',
    'A block is never cut in half by the packer. Half a block does not',
    'render, so the rule is that one always stays whole - which is right',
    'for every block that fits and wrong for the ones that cannot. A long',
    'entry can run half again over a two-column page, and a block that',
    'can neither be broken nor fit gets clipped by the edge of the sheet',
    'instead. Silently, in print, where the warning banner is hidden.',
    '',
    'So Add page breaks cuts an oversize block at a paragraph boundary and',
    'reopens it on the next page, the way a long entry continues in any',
    'printed book. The name repeats with **(continued)** after it, so a',
    'reader landing partway down knows whose entry they are inside and does',
    'not read it as a second one wearing the same name.',
    '',
    'Remove breaks puts the halves back together. So does Add page breaks,',
    'before it lays anything out - otherwise a second press would take each',
    'half for a whole block and cut it again, and the document would grow a',
    'fresh continuation every time you pressed the button.',
    '',
    'A block holding a single paragraph too tall for a sheet has no cut to',
    'make. Those are named in the status line rather than quietly clipped:',
    'shorten the paragraph, or give the page ' + T + 'cols=1' + T + '.',
    '',
    '## Breaking a column',
    '',
    'Columns fill rather than balance: the first runs to the foot of the',
    'page before the second starts, the way a book sets. Where the first',
    'one ends is therefore worth being able to decide, and this decides',
    'it.',
    '',
    F,
    B + 'column',
    F,
    '',
    'Whatever follows starts at the top of the next column. It is your',
    'decision rather than the packer' + APOS + 's, so neither Remove breaks nor',
    'Add page breaks will move it, and a ' + T + B + 'column' + T + ' inside a code fence',
    'is left alone like everything else here.',
    '',
    B + 'page',
    '',
    '# Backgrounds',
    '',
    'Three come with the tool. Each is drawn in the current theme' + APOS + 's own',
    'ink, so it follows the theme and goes grey with the greyscale proof',
    'rather than staying one colour while the page changes around it.',
    '',
    '| Name | What it is |',
    '|---|---|',
    '| ' + T + 'hex' + T + ' | a quiet ground, safe under two columns of body copy |',
    '| ' + T + 'hexdrift' + T + ' | gathered down one side, thinning across the sheet |',
    '| ' + T + 'swarm' + T + ' | cells drifting in a band. A title page, not a text page |',
    '',
    F,
    B + 'page bg=hex',
    B + 'page bg=swarm cols=1',
    F,
    '',
    'None of them reach the edge of the sheet, so nothing of them is',
    'lost at the trim and nothing crowds the page number.',
    '',
    'Anything that is not one of those three names is taken for a URL,',
    'the same way images are, so a background of your own travels with',
    'the document.',
    '',
    F,
    B + 'page bg=https://your-host/art.jpg',
    F,
    '',
    'Strength is set with ' + T + 'tint' + T + ', from 0 to 1. Lower it until the text',
    'over it reads.',
    '',
    F,
    B + 'page bg=hexdrift tint=0.5',
    F,
    '',
    'One line gives the whole document a ground, and any page can still',
    'say otherwise. A page that wants none says so out loud.',
    '',
    F,
    B + 'ground hex tint=0.4',
    '',
    B + 'page bg=none',
    F,
    '',
    'The Ground picker in the toolbar is the same thing from the other',
    'end: it writes ' + T + 'bg=' + T + ' into the page your cursor is in. It is the only',
    'control up there that edits the document rather than the tool,',
    'because a ground is part of what a page looks like and belongs in',
    'the file rather than in a setting you cannot see.',
    '',
    B + 'page bg=hexdrift',
    '',
    '# Grounds of your own',
    '',
    'The three above are one drawing each, the same in every copy of',
    'this tool. Give the document a seed and it draws its own instead.',
    '',
    F,
    B + 'seed 4815',
    F,
    '',
    'Every page using a built-in ground now gets its own drawing, made',
    'from that number. No two match, and the field slides a little from',
    'one page to the next, so page 40 is the same material as page 4 and',
    'plainly not the same picture.',
    '',
    'The seed lives in the document, so none of this is a surprise: the',
    'same file renders the same book on any machine, today and next year.',
    'Change the number and the whole set changes with it.',
    '',
    'One page can be pinned to a seed of its own, whatever the document',
    'says. A cover you have settled on stays settled.',
    '',
    F,
    B + 'page bg=swarm seed=99',
    F,
    '',
    B + 'page',
    '',
    '# Page numbers',
    '',
    'A document has none until it asks for them. One line anywhere in',
    'the file turns them on for the whole of it.',
    '',
    '| Written | What it does |',
    '|---|---|',
    '| ' + T + B + 'folio' + T + ' | numbers from 1, on the outside edge |',
    '| ' + T + B + 'folio center' + T + ' | centred in the bottom margin |',
    '| ' + T + B + 'folio start=5' + T + ' | the first page of this file is page 5 |',
    '| ' + T + B + 'folio off' + T + ' | no numbers, which is what you get anyway |',
    '',
    'The outside edge alternates, so a number never lands in the spine.',
    '',
    'One page can opt out. It keeps its place in the count, the way an',
    'unnumbered plate does in a printed book.',
    '',
    F,
    B + 'page nofolio',
    F,
    '',
    '## Roman front matter',
    '',
    'A page can start the count again, which is how a book gets roman',
    'front matter and then an arabic chapter one. Which numbering you',
    'get is taken from how you write the number, so there is no second',
    'setting to remember: ' + T + 'i' + T + ' is roman, ' + T + '1' + T + ' is arabic.',
    '',
    F,
    B + 'folio start=i',
    '',
    B + 'page folio=1',
    F,
    '',
    'The first opens the document in roman. The second, on the first',
    'page of chapter one, starts again at 1 and stays arabic from there.',
    'Uppercase works the same way, so ' + T + 'folio=I' + T + ' numbers an appendix',
    'I, II, III.',
    '',
    'The Front matter example under Examples in the toolbar is a whole',
    'set of it: half title, title page, credits, copyright, dedication,',
    'a foreword and a table of contents, numbered the way a printed book',
    'numbers them.',
    '',
    '## A book across several files',
    '',
    'The same line lets one book be several documents, a chapter each,',
    'printed separately. Give each file the page it starts on.',
    '',
    F,
    B + 'folio start=12',
    F,
    '',
    'Numbering is not the only thing that follows from this. Which side',
    'of the spine a page falls on is worked out from its number, so a',
    'chapter opening at 12 is laid out as a left-hand page: gutter on the',
    'right, page number on the left, and the page after it the other way',
    'round. Getting that wrong puts the binding margin on the outside',
    'edge of every page in the file, which nothing shows you until it is',
    'printed and bound.',
    '',
    'Two things to keep in step by hand. A chapter that changes length',
    'moves the start of every chapter after it. And a document seed sits',
    'in one file, so give every chapter the same one or their backgrounds',
    'will not look like the same book.',
    '',
    B + 'page cols=1',
    '',
    '# Headings',
    '',
    'Six levels. This page is set to one column, because a level-one',
    'heading spans the full measure by design and would otherwise break',
    'the demonstration in half.',
    '',
    demo('# Heading one'),
    '',
    demo('## Heading two'),
    '',
    demo('### Heading three'),
    '',
    demo('#### Heading four'),
    '',
    demo('##### Heading five'),
    '',
    demo('###### Heading six'),
    '',
    B + 'page',
    '',
    '# Ordinary markdown',
    '',
    '## Emphasis',
    '',
    demo('**bold**, *italic*, ***both***, and `inline code`.'),
    '',
    '## Lists',
    '',
    demo('- a bulleted item', '- another item', '  - and one indented'),
    '',
    demo('1. a numbered item', '2. the next one', '3. and a third'),
    '',
    '## Links',
    '',
    demo('[a link](https://20belowrpg.com)'),
    '',
    '## Blockquotes',
    '',
    demo('> A quotation, or a line of read-aloud text.'),
    '',
    '## Rules',
    '',
    demo('---'),
    '',
    '## Tables',
    '',
    demo(
      '| Element | Splits into |',
      '|---|---|',
      '| Earth | Soak / Potence |',
      '| Moira | Atropos / Klotho |',
    ),
    '',
    '## Images',
    '',
    'Images are referenced by URL, so they travel with the document.',
    '',
    F,
    '![alt text](https://your-host/art.png)',
    F,
    '',
    B + 'page',
    '',
    '# The blocks',
    '',
    'A block is a name, an optional title, and a body. The bare colons',
    'close it, and the body is ordinary markdown.',
    '',
    F,
    '::: name A title',
    'Body markdown.',
    ':::',
    F,
    '',
    'Every name the tool knows is below. The pages after it write each',
    'one out in full, as source and then as result.',
    '',
    '::: wide',
    blockIndex(),
    ':::',
    '',
    B + 'page',
    '',
    '# Box, aside, roll',
    '',
    '## Box',
    '',
    'For something the reader will come back to - a rule, a worked',
    'example, a procedure. The title is what they scan for.',
    '',
    demo(
      '::: box Spending a Fate Token',
      'Declare the spend before the dice land, not after. A Token buys',
      'the reroll. It does not buy the result.',
      ':::',
    ),
    '',
    '## Aside',
    '',
    'For a note beside the argument rather than inside it. Cut an aside',
    'and the page still reads.',
    '',
    demo(
      '::: aside Why Moira, and not Luck',
      'Luck happens to you. Moira is the part of it you have a hand in,',
      'which is why it splits into two sub-stats and not one.',
      ':::',
    ),
    '',
    '## Roll',
    '',
    'Takes no title. Keep it to the line a player looks up in the middle',
    'of a scene.',
    '',
    demo(
      '::: roll',
      'Roll **2d10** under **Attribute + Skill**',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Wide',
    '',
    'Spans both columns. Spanning splits the flow, so text after a wide',
    'block starts again below it rather than carrying on down the',
    'column.',
    '',
    demo(
      '::: wide',
      '| Element | Splits into | Governs |',
      '|---|---|---|',
      '| Earth | Soak / Potence | Force, and what you can take |',
      '| Air | Initiative / Psyche | Speed and clarity |',
      '| Fire | Ferocity / Presence | Push, and how you land |',
      '| Water | Stamina / Health | Endurance and staying up |',
      '| Moira | Atropos / Klotho | Fate, Defense, Ki recovery |',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Figure',
    '',
    'The body is the image, the title is the caption.',
    '',
    demo(
      '::: figure The mark for third-party products',
      '![Powered by 20 Below](https://20belowrpg.com/docs/assets/branding/powered_by_dark.png)',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# The entry blocks',
    '',
    'Five blocks set the five kinds of entry a character is built from -',
    'Skills, Boons, Resources, Flaws and Gifts. They share one shape.',
    '',
    '::: box What every entry block does',
    '**The title** names the entry, and carries a second piece of',
    'information for a Skill (its Element) and a Boon (its cost).',
    '',
    '**The first paragraph** is the flavour line, and is set apart from',
    'what follows. An entry written as a single paragraph is all rule and',
    'no flavour, which is fine.',
    '',
    '**The paragraphs after it** are the rule. One opening with a bold',
    'number is a level and gets that number in a badge. One opening with',
    'a bold Tier is a purchase tier. Bold Adders or Limiters alone on a',
    'line opens a labelled run. Anything else stays ordinary prose.',
    ':::',
    '',
    'Nothing is marked up twice. The Element in a Skill title sets the',
    'colour of the entry, so the colour can never disagree with the text',
    'beside it, and the cost in a Boon title becomes the pill.',
    '',
    B + 'page',
    '',
    '## Skill',
    '',
    'Title it ' + T + 'Name (Element)' + T + '.',
    '',
    demo(
      '::: skill Escapology (Water)',
      'Rope, cuffs, the trunk of a car. The trick is never strength. It',
      'is knowing which part of you has to go soft, and in what order.',
      '',
      'Breaking free of restraints and confined spaces under pressure.',
      'The GM sets Difficulty from the restraint itself - a knot tied by',
      'an amateur is not handcuffs, and handcuffs are not a chain',
      'somebody welded shut.',
      ':::',
    ),
    '',
    '## Boon',
    '',
    'Title it ' + T + 'Name (cost)' + T + '. Most Boons are a flat cost, written',
    'like ' + T + 'Alertness (3, Lesser)' + T + '. Sixteen are bought as one of',
    'several tiers instead, and those lines are lifted onto their own',
    'strips so a reader can see the structure without reading for it.',
    '',
    demo(
      '::: boon Innate Compass (1 or 3)',
      'You have never once had to ask which way you were facing.',
      '',
      'Bought as one of two tiers. The higher includes the lower, so',
      'there is no need to buy both.',
      '',
      '**Tier 1** (1, Trivial): you always know true north, and roughly',
      'what time it is, wherever you are.',
      '',
      '**Tier 2** (3, Lesser): for anywhere you have been before, you',
      'also know the direction to it and roughly how far.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Resource',
    '',
    'Every Resource is rated 1 to 5, and the ladder is the substance of',
    'the entry. The summary line above the levels is ordinary prose.',
    '',
    demo(
      '::: resource Contacts',
      'Everybody knows somebody. The only question is how far the',
      'somebodies reach.',
      '',
      'How large, how capable, and how well placed the network is.',
      '',
      '**1** One reliable contact, good for small favors and small news.',
      '',
      '**2** A handful of contacts spanning a couple of fields.',
      '',
      '**3** A broad network reaching across most of a city.',
      '',
      '**4** An extensive network with regional reach, including a few',
      'names with real influence.',
      '',
      '**5** A network reaching into any field or region that matters,',
      'including people who are used to being obeyed.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Flaw',
    '',
    'Built like a Resource and rated the same way, but tinted danger.',
    'Somebody flicking through should never mistake a Flaw for something',
    'they are buying.',
    '',
    demo(
      '::: flaw Directionless',
      'You have been turned around in your own neighborhood, sober, in',
      'daylight. It stopped being funny some time ago.',
      '',
      'A poor and unreliable sense of direction. Points granted equal the',
      'level taken.',
      '',
      '**1** Occasionally turned around, even somewhere familiar. Rarely',
      'costs more than a moment.',
      '',
      '**2** Regularly lost in unfamiliar areas. Directions get checked',
      'rather than trusted.',
      '',
      '**3** Lost in semi-familiar places without a map, a guide, or',
      'somebody to follow.',
      '',
      '**4** Cannot reliably walk a short familiar route unaided, and any',
      'pressure makes it worse.',
      '',
      '**5** No functional sense of direction at all. In the dark, under',
      'stress, you could lose your own house.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Gift',
    '',
    'The largest entries in the book. Five levels, then Adders and',
    'Limiters, which are labelled runs rather than numbered ones.',
    '',
    F,
    '::: gift Jumping',
    'Flavour line.',
    '',
    '**1** What the first level does.',
    '',
    '**Adders**',
    '',
    '- **Name** (Lesser, 3 pts): what it adds.',
    '',
    '**Limiters**',
    '',
    '- **Name**: what it costs you.',
    ':::',
    F,
    '',
    'Written out in full, that produces this.',
    '',
    '::: gift Jumping',
    'You do not run to the edge and jump. You just jump. One push clears',
    'a rooftop, a ravine, whatever happens to be in the way.',
    '',
    '**1** From standing, jump forward up to **2x** your Movement Rate,',
    'or straight up **1x**. A Fast action. No fall damage from a landing',
    'height within what you could jump. No Ki, no Gift Check.',
    '',
    '**2** Forward jumps extend to **3x** Movement Rate, vertical to',
    '**1.5x**. You can adjust your trajectory once, mid-air.',
    '',
    '**3** Forward jumps extend to **4x**, vertical to **2x**. Spend',
    '**1 Ki** to chain a second jump on landing, covering that distance',
    'again in the same move.',
    '',
    '**4** Forward jumps extend to **6x**, vertical to **3x**. A landing',
    'can be an attack: spend **1 Ki**, and everyone within Close range of',
    'where you come down takes your Potence dice against their Soak.',
    'Chaining a jump no longer costs Ki.',
    '',
    '**5** Forward jumps extend to **10x**, vertical to **5x**. The',
    'landing attack costs no Ki.',
    '',
    '**Adders**',
    '',
    '- **Wall Launch** (Lesser, 3 pts): kick off a vertical surface',
    'mid-jump to redirect, adding a second full jump distance to the same',
    'move, no Ki.',
    '',
    '- **Silent Landing** (Lesser, 3 pts): land without sound or visible',
    'impact. No dust, no thud, no sign you came down here.',
    '',
    '- **Shockwave Leap** (Greater, 6 pts): the landing attack becomes a',
    'Near-range area effect, for an extra 1 Ki.',
    '',
    '**Limiters**',
    '',
    '- **Committed Arc**: once a jump begins you cannot abort or land',
    'early. You cover the distance you committed to.',
    '',
    '- **Self-Inflicted Impact**: the landing attack also hits you for',
    'half the dice rolled.',
    '',
    '- **No Redirect**: the mid-air adjustment never applies.',
    ':::',
    '',
    B + 'page',
    '',
    '# Stat blocks',
    '',
    'A stat block pastes in from the Adversary Index unchanged. The line',
    'of figures is picked out on its own - it is recognised by the middot',
    'separators the index already uses, so there is nothing to rewrite.',
    '',
    demo(
      '::: stat.danger Rougarou',
      'A cursed shape that runs the batture at night, and is somebody',
      'local in the morning.',
      '',
      '**Soak** 3 \u00b7 **Attack** 7 \u00b7 **Defense** 6 \u00b7 **Health Levels** 7 \u00b7 **Movement Rate** 12m',
      '',
      '**Claws/Bite**: 7, Melee',
      '',
      '**Notable Skills**: Athletics 9, Stealth 8, Perception 8',
      '',
      '**Traits**: **Regenerates** - heals 1 Health Level at the start of',
      'each of its turns, unless its most recent wound came from a weapon',
      'the GM has ruled counts as silver.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Colour',
    '',
    'Any block takes a colour from the style guide, written after a dot.',
    '',
    F,
    '::: box.danger A title',
    '::: roll.fire',
    '::: aside.moira A title',
    F,
    '',
    '::: box.danger A danger box',
    'Danger and npc share the red from the Battle Tracker.',
    ':::',
    '',
    '::: aside.water A water aside',
    'Colour tints the rule and the title, not the fill, so body text',
    'keeps its contrast.',
    ':::',
    '',
    '## Every colour',
    '',
    colourDemos(),
    '',
    '::: aside In greyscale',
    'Every colour collapses to one grey. A black and white print cannot',
    'carry nine hues, so say in words what the colour would have said.',
    ':::',
    '',
    B + 'page cols=1',
    '',
    '# Publishing what you make',
    '',
    '20 Below is released under the ORC License. You may publish material',
    'for it - free or commercial - without asking permission. What the',
    'licence asks in return is that your product carries these notices.',
    '',
    '::: box Required in your product',
    '**ORC Notice.** This product is licensed under the ORC License located',
    'at the Library of Congress at TX 9-307-067 and available online at',
    'various locations including azoralaw.com/orclicense and others. All',
    'warranties are disclaimed as set forth therein.',
    '',
    '**Attribution.** This product is based on the following Licensed',
    'Material: 20 Below Core Rules, Copyright (c) 2026 Feralucce Savage.',
    '',
    '**Reserved Material.** List anything in your own product you are',
    'reserving - your setting, characters, art and branding.',
    ':::',
    '',
    '::: aside.danger What is not licensed',
    'The ORC licenses game mechanics, not branding. The name **20 Below**,',
    'its logos and its trade dress are Reserved Material, and no trademark',
    'rights pass under the ORC at all. Using them, or implying that your',
    'product is endorsed or official, needs separate permission.',
    ':::',
    '',
    '::: aside.pc Powered by 20 Below',
    'There is a brand mark for products made for this system. It is opt-in',
    'and granted separately from the ORC - ask, agree to the brand terms,',
    'and you may carry it. Publishing under the ORC alone does not include',
    'it, and does not require it.',
    ':::',
    '',
    'The full licence, and what is open versus reserved, is on the Licence',
    'page linked in the toolbar.',
    '',
    B + 'page cols=1 bg=swarm nofolio',
    '',
    '# A single-column page',
    '',
    'Set with ' + T + B + 'page cols=1' + T + ' when a page wants the full measure - a',
    'title page, a full-page illustration, or a long table that reads',
    'better wide.',
    '',
    'This one is the whole of it at once. One column, the ' + T + 'swarm' + T,
    'ground, and no page number: it is set ' + T + 'nofolio' + T + ', which is what a',
    'title page usually wants. It still counts, so the numbering does',
    'not skip.',
    '',
    F,
    B + 'page cols=1 bg=swarm nofolio',
    F,
    '',
  ].join('\n');
}
