const V = new URL(import.meta.url).search;
const { blockHelp, VARIANTS } = await import('./blocks.js' + V);

/* Two documents.
 *
 *   guide()   - the visual reference. Everything the tool can do,
 *               shown as source and then as the result it produces.
 *               Opened in its own window by the Reference button, and
 *               loaded on a first visit.
 *   starter() - what the New button gives you. Deliberately almost
 *               empty; the reference is a click away.
 *
 * The block and colour lists are generated from blocks.js, so adding
 * either one documents itself with no second place to update.
 */

const B = String.fromCharCode(92);            // a single backslash
const F = String.fromCharCode(96).repeat(3);  // a code fence
const T = String.fromCharCode(96);            // one backtick, inline code

/* Source, then the same source rendered. The point of the guide is
 * that you never have to imagine the result. */
function demo(...lines) {
  return [F, ...lines, F, '', ...lines].join('\n');
}

/* One row per block, generated from blocks.js, so a block added there
 * is listed here without a second place to update. The worked entries
 * further down are written by hand - the table says what exists, the
 * entries show what each one looks like. */
function blockIndex() {
  return [
    '| Block | Title | What it is for |',
    '|---|---|---|',
    ...blockHelp().map((b) =>
      '| ' + T + b.name + T + ' | ' + (b.takesTitle ? 'yes' : '-') + ' | ' + b.help + ' |'),
  ].join('\n');
}

/* One roll box per colour, labelled with its own name. */
function colourDemos() {
  return VARIANTS.filter((v) => v !== 'npc')
    .map((v) => ['::: roll.' + v, v.charAt(0).toUpperCase() + v.slice(1), ':::'].join('\n'))
    .join('\n\n');
}

/* One page that touches every themed token, for themes.html to render
 * side by side. Deliberately short and dense: a theme is judged on how
 * a heading sits against body copy, how a rule reads against the page,
 * and whether a boxed panel still separates from the ground - not on
 * how much text fits. The caller passes cols=1, and this has to fit a
 * single 6x9 page without spilling into a second column, so keep it
 * tight when adding to it.
 */
export function themeSample() {
  return [
    '# Deep Water',
    '',
    'Body copy sets the register of a theme more than any heading does.',
    'Read at size, against the page ground, with a [link](#) and some',
    T + 'inline code' + T + ' in it.',
    '',
    '## Second level',
    '',
    '### Third level, which takes the accent',
    '',
    '> A blockquote leans on the accent for its rule and the dim text',
    '> colour for its body.',
    '',
    '::: box A boxed callout',
    'Panel against page. These two sit close together on purpose, so',
    'this is where a greyscale ramp fails first.',
    ':::',
    '',
    '::: aside',
    'An aside is the accent doing structural work, not decorative.',
    ':::',
    '',
    '| Column | Reads against |',
    '|---|---|',
    '| Header row | the second panel tone |',
    '| Body row | the page ground |',
    '',
    '::: stat Marsh Revenant',
    'Health 5 | Soak 3 | Ferocity 4',
    'The stat line is what a GM scans mid-fight, so it has to stay',
    'legible in every theme and both palettes.',
    ':::',
    '',
    '::: roll.pc',
    'Roll boxes carry the variant colours',
    ':::',
    '',
  ].join('\n');
}

export function starter() {
  return [
    '# Title',
    '',
    'Start writing. Two columns by default; the Reference button opens',
    'a guide to everything the tool can do.',
    '',
  ].join('\n');
}

export function guide() {
  return [
    '# The Brewery',
    '',
    'Everything this tool can do, shown as the markdown that produces it',
    'and then as the result. Pages are two columns by default.',
    '',
    '## Two markers',
    '',
    'The whole syntax is two things.',
    '',
    F,
    B + 'page',
    B + 'page cols=1',
    B + 'page bg=parchment',
    '',
    '::: name A title',
    ':::',
    F,
    '',
    'The first starts a new page - as one column, or with a background,',
    'if you say so. The second opens a block; the bare colons close it.',
    '',
    B + 'page cols=1',
    '',
    '# Headings',
    '',
    'Six levels. This page is set to one column, because a level-one',
    'heading spans the full measure by design and would otherwise break',
    'the demonstration in half.',
    '',
    demo('# Heading one'),
    '',
    demo('## Heading two'),
    '',
    demo('### Heading three'),
    '',
    demo('#### Heading four'),
    '',
    demo('##### Heading five'),
    '',
    demo('###### Heading six'),
    '',
    B + 'page',
    '',
    '# Ordinary markdown',
    '',
    '## Emphasis',
    '',
    demo('**bold**, *italic*, ***both***, and `inline code`.'),
    '',
    '## Lists',
    '',
    demo('- a bulleted item', '- another item', '  - and one indented'),
    '',
    demo('1. a numbered item', '2. the next one', '3. and a third'),
    '',
    '## Links',
    '',
    demo('[a link](https://20belowrpg.com)'),
    '',
    '## Blockquotes',
    '',
    demo('> A quotation, or a line of read-aloud text.'),
    '',
    '## Rules',
    '',
    demo('---'),
    '',
    '## Tables',
    '',
    demo(
      '| Element | Splits into |',
      '|---|---|',
      '| Earth | Soak / Potence |',
      '| Moira | Atropos / Klotho |',
    ),
    '',
    '## Images',
    '',
    'Images are referenced by URL, so they travel with the document.',
    '',
    F,
    '![alt text](https://your-host/art.png)',
    F,
    '',
    B + 'page',
    '',
    '# The blocks',
    '',
    'A block is a name, an optional title, and a body. The bare colons',
    'close it, and the body is ordinary markdown.',
    '',
    F,
    '::: name A title',
    'Body markdown.',
    ':::',
    F,
    '',
    'Every name the tool knows is below. The pages after it write each',
    'one out in full, as source and then as result.',
    '',
    '::: wide',
    blockIndex(),
    ':::',
    '',
    B + 'page',
    '',
    '# Box, aside, roll',
    '',
    '## Box',
    '',
    'For something the reader will come back to - a rule, a worked',
    'example, a procedure. The title is what they scan for.',
    '',
    demo(
      '::: box Spending a Fate Token',
      'Declare the spend before the dice land, not after. A Token buys',
      'the reroll. It does not buy the result.',
      ':::',
    ),
    '',
    '## Aside',
    '',
    'For a note beside the argument rather than inside it. Cut an aside',
    'and the page still reads.',
    '',
    demo(
      '::: aside Why Moira, and not Luck',
      'Luck happens to you. Moira is the part of it you have a hand in,',
      'which is why it splits into two sub-stats and not one.',
      ':::',
    ),
    '',
    '## Roll',
    '',
    'Takes no title. Keep it to the line a player looks up in the middle',
    'of a scene.',
    '',
    demo(
      '::: roll',
      'Roll **2d10** under **Attribute + Skill**',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Wide',
    '',
    'Spans both columns. Spanning splits the flow, so text after a wide',
    'block starts again below it rather than carrying on down the',
    'column.',
    '',
    demo(
      '::: wide',
      '| Element | Splits into | Governs |',
      '|---|---|---|',
      '| Earth | Soak / Potence | Force, and what you can take |',
      '| Air | Initiative / Psyche | Speed and clarity |',
      '| Fire | Ferocity / Presence | Push, and how you land |',
      '| Water | Stamina / Health | Endurance and staying up |',
      '| Moira | Atropos / Klotho | Fate, Defense, Ki recovery |',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Figure',
    '',
    'The body is the image, the title is the caption.',
    '',
    demo(
      '::: figure The mark for third-party products',
      '![Powered by 20 Below](https://20belowrpg.com/docs/assets/branding/powered_by_dark.png)',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# The entry blocks',
    '',
    'Five blocks set the five kinds of entry a character is built from -',
    'Skills, Boons, Resources, Flaws and Gifts. They share one shape.',
    '',
    '::: box What every entry block does',
    '**The title** names the entry, and carries a second piece of',
    'information for a Skill (its Element) and a Boon (its cost).',
    '',
    '**The first paragraph** is the flavour line, and is set apart from',
    'what follows. An entry written as a single paragraph is all rule and',
    'no flavour, which is fine.',
    '',
    '**The paragraphs after it** are the rule. One opening with a bold',
    'number is a level and gets that number in a badge. One opening with',
    'a bold Tier is a purchase tier. Bold Adders or Limiters alone on a',
    'line opens a labelled run. Anything else stays ordinary prose.',
    ':::',
    '',
    'Nothing is marked up twice. The Element in a Skill title sets the',
    'colour of the entry, so the colour can never disagree with the text',
    'beside it, and the cost in a Boon title becomes the pill.',
    '',
    B + 'page',
    '',
    '## Skill',
    '',
    'Title it ' + T + 'Name (Element)' + T + '.',
    '',
    demo(
      '::: skill Escapology (Water)',
      'Rope, cuffs, the trunk of a car. The trick is never strength. It',
      'is knowing which part of you has to go soft, and in what order.',
      '',
      'Breaking free of restraints and confined spaces under pressure.',
      'The GM sets Difficulty from the restraint itself - a knot tied by',
      'an amateur is not handcuffs, and handcuffs are not a chain',
      'somebody welded shut.',
      ':::',
    ),
    '',
    '## Boon',
    '',
    'Title it ' + T + 'Name (cost)' + T + '. Most Boons are a flat cost, written',
    'like ' + T + 'Alertness (3, Lesser)' + T + '. Sixteen are bought as one of',
    'several tiers instead, and those lines are lifted onto their own',
    'strips so a reader can see the structure without reading for it.',
    '',
    demo(
      '::: boon Innate Compass (1 or 3)',
      'You have never once had to ask which way you were facing.',
      '',
      'Bought as one of two tiers. The higher includes the lower, so',
      'there is no need to buy both.',
      '',
      '**Tier 1** (1, Trivial): you always know true north, and roughly',
      'what time it is, wherever you are.',
      '',
      '**Tier 2** (3, Lesser): for anywhere you have been before, you',
      'also know the direction to it and roughly how far.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Resource',
    '',
    'Every Resource is rated 1 to 5, and the ladder is the substance of',
    'the entry. The summary line above the levels is ordinary prose.',
    '',
    demo(
      '::: resource Contacts',
      'Everybody knows somebody. The only question is how far the',
      'somebodies reach.',
      '',
      'How large, how capable, and how well placed the network is.',
      '',
      '**1** One reliable contact, good for small favors and small news.',
      '',
      '**2** A handful of contacts spanning a couple of fields.',
      '',
      '**3** A broad network reaching across most of a city.',
      '',
      '**4** An extensive network with regional reach, including a few',
      'names with real influence.',
      '',
      '**5** A network reaching into any field or region that matters,',
      'including people who are used to being obeyed.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Flaw',
    '',
    'Built like a Resource and rated the same way, but tinted danger.',
    'Somebody flicking through should never mistake a Flaw for something',
    'they are buying.',
    '',
    demo(
      '::: flaw Directionless',
      'You have been turned around in your own neighborhood, sober, in',
      'daylight. It stopped being funny some time ago.',
      '',
      'A poor and unreliable sense of direction. Points granted equal the',
      'level taken.',
      '',
      '**1** Occasionally turned around, even somewhere familiar. Rarely',
      'costs more than a moment.',
      '',
      '**2** Regularly lost in unfamiliar areas. Directions get checked',
      'rather than trusted.',
      '',
      '**3** Lost in semi-familiar places without a map, a guide, or',
      'somebody to follow.',
      '',
      '**4** Cannot reliably walk a short familiar route unaided, and any',
      'pressure makes it worse.',
      '',
      '**5** No functional sense of direction at all. In the dark, under',
      'stress, you could lose your own house.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '## Gift',
    '',
    'The largest entries in the book. Five levels, then Adders and',
    'Limiters, which are labelled runs rather than numbered ones.',
    '',
    F,
    '::: gift Jumping',
    'Flavour line.',
    '',
    '**1** What the first level does.',
    '',
    '**Adders**',
    '',
    '- **Name** (Lesser, 3 pts): what it adds.',
    '',
    '**Limiters**',
    '',
    '- **Name**: what it costs you.',
    ':::',
    F,
    '',
    'Written out in full, that produces this.',
    '',
    '::: gift Jumping',
    'You do not run to the edge and jump. You just jump. One push clears',
    'a rooftop, a ravine, whatever happens to be in the way.',
    '',
    '**1** From standing, jump forward up to **2x** your Movement Rate,',
    'or straight up **1x**. A Fast action. No fall damage from a landing',
    'height within what you could jump. No Ki, no Gift Check.',
    '',
    '**2** Forward jumps extend to **3x** Movement Rate, vertical to',
    '**1.5x**. You can adjust your trajectory once, mid-air.',
    '',
    '**3** Forward jumps extend to **4x**, vertical to **2x**. Spend',
    '**1 Ki** to chain a second jump on landing, covering that distance',
    'again in the same move.',
    '',
    '**4** Forward jumps extend to **6x**, vertical to **3x**. A landing',
    'can be an attack: spend **1 Ki**, and everyone within Close range of',
    'where you come down takes your Potence dice against their Soak.',
    'Chaining a jump no longer costs Ki.',
    '',
    '**5** Forward jumps extend to **10x**, vertical to **5x**. The',
    'landing attack costs no Ki.',
    '',
    '**Adders**',
    '',
    '- **Wall Launch** (Lesser, 3 pts): kick off a vertical surface',
    'mid-jump to redirect, adding a second full jump distance to the same',
    'move, no Ki.',
    '',
    '- **Silent Landing** (Lesser, 3 pts): land without sound or visible',
    'impact. No dust, no thud, no sign you came down here.',
    '',
    '- **Shockwave Leap** (Greater, 6 pts): the landing attack becomes a',
    'Near-range area effect, for an extra 1 Ki.',
    '',
    '**Limiters**',
    '',
    '- **Committed Arc**: once a jump begins you cannot abort or land',
    'early. You cover the distance you committed to.',
    '',
    '- **Self-Inflicted Impact**: the landing attack also hits you for',
    'half the dice rolled.',
    '',
    '- **No Redirect**: the mid-air adjustment never applies.',
    ':::',
    '',
    B + 'page',
    '',
    '# Stat blocks',
    '',
    'A stat block pastes in from the Adversary Index unchanged. The line',
    'of figures is picked out on its own - it is recognised by the middot',
    'separators the index already uses, so there is nothing to rewrite.',
    '',
    demo(
      '::: stat.danger Rougarou',
      'A cursed shape that runs the batture at night, and is somebody',
      'local in the morning.',
      '',
      '**Soak** 3 \u00b7 **Attack** 7 \u00b7 **Defense** 6 \u00b7 **Health Levels** 7 \u00b7 **Movement Rate** 12m',
      '',
      '**Claws/Bite**: 7, Melee',
      '',
      '**Notable Skills**: Athletics 9, Stealth 8, Perception 8',
      '',
      '**Traits**: **Regenerates** - heals 1 Health Level at the start of',
      'each of its turns, unless its most recent wound came from a weapon',
      'the GM has ruled counts as silver.',
      ':::',
    ),
    '',
    B + 'page',
    '',
    '# Colour',
    '',
    'Any block takes a colour from the style guide, written after a dot.',
    '',
    F,
    '::: box.danger A title',
    '::: roll.fire',
    '::: aside.moira A title',
    F,
    '',
    '::: box.danger A danger box',
    'Danger and npc share the red from the Battle Tracker.',
    ':::',
    '',
    '::: aside.water A water aside',
    'Colour tints the rule and the title, not the fill, so body text',
    'keeps its contrast.',
    ':::',
    '',
    '## Every colour',
    '',
    colourDemos(),
    '',
    '::: aside In greyscale',
    'Every colour collapses to one grey. A black and white print cannot',
    'carry nine hues, so say in words what the colour would have said.',
    ':::',
    '',
    B + 'page cols=1',
    '',
    '# Publishing what you make',
    '',
    '20 Below is released under the ORC License. You may publish material',
    'for it - free or commercial - without asking permission. What the',
    'licence asks in return is that your product carries these notices.',
    '',
    '::: box Required in your product',
    '**ORC Notice.** This product is licensed under the ORC License located',
    'at the Library of Congress at TX 9-307-067 and available online at',
    'various locations including azoralaw.com/orclicense and others. All',
    'warranties are disclaimed as set forth therein.',
    '',
    '**Attribution.** This product is based on the following Licensed',
    'Material: 20 Below Core Rules, Copyright (c) 2026 Feralucce Savage.',
    '',
    '**Reserved Material.** List anything in your own product you are',
    'reserving - your setting, characters, art and branding.',
    ':::',
    '',
    '::: aside.danger What is not licensed',
    'The ORC licenses game mechanics, not branding. The name **20 Below**,',
    'its logos and its trade dress are Reserved Material, and no trademark',
    'rights pass under the ORC at all. Using them, or implying that your',
    'product is endorsed or official, needs separate permission.',
    ':::',
    '',
    '::: aside.pc Powered by 20 Below',
    'There is a brand mark for products made for this system. It is opt-in',
    'and granted separately from the ORC - ask, agree to the brand terms,',
    'and you may carry it. Publishing under the ORC alone does not include',
    'it, and does not require it.',
    ':::',
    '',
    'The full licence, and what is open versus reserved, is on the Licence',
    'page linked in the toolbar.',
    '',
    B + 'page cols=1',
    '',
    '# A single-column page',
    '',
    'Set with ' + T + B + 'page cols=1' + T + ' when a page wants the full measure - a',
    'title page, a full-page illustration, or a long table that reads',
    'better wide.',
    '',
  ].join('\n');
}
