# -*- coding: utf-8 -*-
"""Manuscript -> the web edition, in webbook/.

The book is the source. webbook/ is build output and is never hand-edited -
edits belong in the Scrivener project, and this regenerates from it.

Not to be confused with rules/, which is the machine-readable contract the
character creator parses and is authored separately. The two say the same
things in different registers, and only rules/ can break the app.

Emits one markdown file per chapter with Jekyll front matter, so the site
renders it through _layouts/webbook.html the same way rules/ renders through
_layouts/rules.html. Chapters are listed explicitly rather than discovered:
publishing is a decision, not a side effect of a chapter existing.

    python tools/scriv2web.py
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "webbook")

sys.path.insert(0, HERE)
from scriv2brew import chapter_uuid, to_chunks   # noqa: E402

# (binder fragment, url slug, nav section, page title)
#
# Chapter 13 is deliberately absent. It is a 400-word stub, and the web
# edition should not publish a chapter that is visibly unwritten. Add it here
# when it is finished; nothing else needs changing.
CHAPTERS = [
    ("Chapter 01", "introduction",         "start",   "Introduction"),
    ("Chapter 02", "glossary",             "start",   "Glossary"),
    ("Chapter 03", "creating-a-character", "start",   "Creating a Character"),
    ("Chapter 04", "how-to-play",          "start",   "How to Play"),
    ("Chapter 05", "skills",               "options", "Skills"),
    ("Chapter 06", "boons",                "options", "Boons"),
    ("Chapter 07", "resources",            "options", "Resources"),
    ("Chapter 08", "gifts",                "options", "Gifts"),
    ("Chapter 09", "flaws",                "options", "Flaws"),
    ("Chapter 10", "fate",                 "combat",  "Fate"),
    ("Chapter 11", "equipment",            "combat",  "Weapons & Equipment"),
    ("Chapter 12", "advancement",          "options", "Advancement"),
]

BANNER = ("<!-- Generated by tools/scriv2web.py from the Scrivener manuscript.\n"
          "     Do not hand-edit: the next run overwrites it. Edit the book. -->\n")


def rules_tables(path):
    """Every markdown table in a rules file, indexed by its first column.

    Returns [(header, separator, {first_cell_lower: row_line})] in file order.
    """
    tables = []
    header = sep = None
    rows = {}
    for line in io.open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if header is None:
                header = line
            elif sep is None and set(line.replace("|", "").strip()) <= set("-: "):
                sep = line
            elif cells and cells[0]:
                rows[cells[0].lower()] = line
        else:
            if header and sep and rows:
                tables.append((header, sep, rows))
            header = sep = None
            rows = {}
    if header and sep and rows:
        tables.append((header, sep, rows))
    return tables


ROW = re.compile(r"^\*\*([^*\n]+)\*\* - ")


def row_name(chunk):
    """The item name, if this chunk is a flattened table row.

    Anchored on purpose. Testing for '** - ' anywhere in the text also matches
    ordinary prose that happens to bold a term and use a dash later in the
    sentence, and one of those swallowed the entire weapons table.
    """
    if "\n" in chunk:
        return None
    m = ROW.match(chunk)
    if not m:
        return None
    name = m.group(1).strip().lower()
    # A purely numeric key is not a name, it is a position, and every numbered
    # table in the project shares it. Matching on one spliced the adversary
    # index's mutation table into 49 Gifts, whose level lines open "**1**".
    if not name or name.strip(".").isdigit():
        return None
    return name


def restore_tables(chunks, tables):
    """Rebuild flattened rows as real tables, using the rules file's headers.

    The manuscript stores its tables as one dash-separated line per row, and
    those do not split back into columns reliably - "Melee - - - - - 1" is
    four empty cells or five depending on how you read it. rules/*.md holds
    the same data as proper tables, so the columns come from there. Only rows
    the book actually lists are emitted, in the book's order: this restores
    structure, it does not add content.
    """
    def table_for(name):
        for t in tables:
            if name in t[2]:
                return t
        return None

    out = []
    built = None          # (header, sep, [row lines]) currently being filled
    owner = None          # the table those rows came from

    def flush():
        if built and len(built) > 2:
            out.append("\n".join(built))

    for chunk in chunks:
        name = row_name(chunk)
        found = table_for(name) if name else None
        if found is None:
            # Not a row of any table we know - a gear package, or prose.
            flush(); built = owner = None
            out.append(chunk)
            continue
        if found is not owner:
            flush()
            owner = found
            built = [found[0], found[1]]
        built.append(found[2][name])
    flush()

    # The manuscript's own header row survives the flattening as prose - a
    # line like "**Option** - Cost - Effect" sitting above the table it used
    # to head. Drop it where the table right below already says the same.
    cleaned = []
    for j, chunk in enumerate(out):
        nxt = out[j + 1] if j + 1 < len(out) else ""
        name = row_name(chunk)
        if name and nxt.startswith("|"):
            first_cell = nxt.split("\n")[0].strip("|").split("|")[0].strip().lower()
            if name == first_cell:
                continue
        cleaned.append(chunk)
    return cleaned


# An entry as the book writes it: "**Amnesia (= Level).** *flavour line*",
# then its description, then any "**1**..**5**" level lines. The same shape
# The Brewery's entry blocks render, so the web edition renders it the same
# way - flavour set apart, the whole thing boxed.
ENTRY = re.compile(r"^\*\*([^*]+?)\.\*\*\s+\*(.+)\*$")
NAME_TAG = re.compile(r"^(.*?)\s*\(([^()]*)\)\s*$")


def wrap_entries(chunks):
    """Box each entry, so a reader can see where one stops and the next starts."""
    out = []
    i = 0
    while i < len(chunks):
        m = ENTRY.match(chunks[i])
        if not m:
            out.append(chunks[i]); i += 1; continue
        name, flavour = m.group(1).strip(), m.group(2).strip()
        tag = ""
        nt = NAME_TAG.match(name)
        if nt:
            name, tag = nt.group(1).strip(), nt.group(2).strip()
        i += 1
        body = []
        while i < len(chunks) and not chunks[i].startswith("#") and not ENTRY.match(chunks[i]):
            body.append(chunks[i]); i += 1
        head = '<p class="entry-head"><span class="entry-name">%s</span>%s</p>' % (
            name, ('<span class="entry-tag">%s</span>' % tag) if tag else "")
        card = ['<div class="entry" markdown="1">', head,
                '<p class="entry-flavour">%s</p>' % flavour]
        if body:
            card.append("")
            card.append("\n\n".join(body))
        card.append("</div>")
        out.append("\n".join(card))
    return out


def gift_lists(path):
    """Per Gift, its Adders and Limiters as the rules file bullets them.

    The manuscript runs all three Adders together in one paragraph, so on the
    page they arrive as a wall - "...no Ki cost. **Silent Landing** (Lesser,
    3 pts): land without...". Splitting that back apart by punctuation is
    guesswork; rules/gifts.md already has them as a list, one per line.
    """
    text = io.open(path, encoding="utf-8").read()
    out = {}
    for section in text.split("\n### ")[1:]:
        name = section.split("\n", 1)[0].strip()
        lists = {}
        # Bulleted labels, and the tabled ones. "Pool by Level" is keyed 1..5,
        # which is why the general table restorer will not touch it - every
        # numbered table in the project shares those keys. Here the Gift is
        # known by name, so its own table is unambiguous.
        for label in ("Adders", "Limiters", "Pool by Level", "Build menu"):
            m = re.search(r"^\*\*%s\*\*:?\s*$" % re.escape(label), section, re.M)
            if not m:
                continue
            block = []
            for line in section[m.end():].split("\n"):
                if line.startswith("- ") or line.startswith("|"):
                    block.append(line)
                elif block and line.strip():
                    break
            if block:
                lists[label] = "\n".join(block)
        out[name] = lists
    return out


LABELS = ("Adders", "Limiters", "Pool by Level", "Build menu")
POOL_ROW = re.compile(r"^\*\*\d+\*\*\s*-\s*\d+\s*points\.?$")


def relist(body, lists):
    """Swap what the manuscript flattened for the rules file's own version.

    Each label owns a different amount of what follows it, so each is consumed
    on its own terms: Adders and Limiters are one run-together paragraph, the
    pool is five numbered lines, the build menu is a table. Consuming by "skip
    until the next label" instead would swallow the Gift's level lines, which
    sit after the Limiters with nothing to mark where they start.
    """
    out = []
    i = 0
    while i < len(body):
        chunk = body[i]
        label = chunk.strip("*: ").strip()
        if not (chunk.startswith("**") and label in LABELS and lists.get(label)):
            out.append(chunk); i += 1
            continue
        out.append(chunk)
        out.append(lists[label])
        i += 1
        if label in ("Adders", "Limiters"):
            if i < len(body) and body[i].strip("*: ").strip() not in LABELS:
                i += 1
        elif label == "Pool by Level":
            while i < len(body) and POOL_ROW.match(body[i]):
                i += 1
        elif label == "Build menu":
            while i < len(body) and (
                body[i].startswith("|")
                or (body[i].startswith("**") and " - " in body[i]
                    and "\n" not in body[i] and not POOL_ROW.match(body[i]))
            ):
                i += 1
    return out


def wrap_headed_entries(chunks, after, lists_by_name=None):
    """Box every "## Name" section following `after`, one card each.

    Gifts are not written like Skills or Boons - each is a heading with its
    flavour, Adders, Limiters and levels beneath it, not a single bolded
    lead-in. So they are boxed by section instead, in the same card, and the
    heading stays a real heading inside it: the anchor keeps working and the
    chapter still has an outline.
    """
    try:
        start = chunks.index(after)
    except ValueError:
        return chunks
    out = chunks[:start + 1]
    i = start + 1
    while i < len(chunks):
        if not chunks[i].startswith("## "):
            out.append(chunks[i]); i += 1; continue
        head = chunks[i]
        i += 1
        body = []
        while i < len(chunks) and not chunks[i].startswith("## "):
            body.append(chunks[i]); i += 1
        if lists_by_name:
            body = relist(body, lists_by_name.get(head[3:].strip(), {}))
        card = ['<div class="entry entry-headed" markdown="1">', "", head, ""]
        if body and body[0].startswith("*") and body[0].endswith("*") and "\n" not in body[0]:
            card.append('<p class="entry-flavour">%s</p>' % body[0].strip("*").strip())
            body = body[1:]
        if body:
            card.append("")
            card.append("\n\n".join(body))
        card.append("</div>")
        out.append("\n".join(card))
    return out


def yaml_quote(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def body_of(chunks):
    """Everything but the chapter title - the layout renders that from the
    front matter, so leaving it in would print the heading twice."""
    out = list(chunks)
    if out and out[0].startswith("# "):
        out = out[1:]
    return "\n\n".join(out).strip() + "\n"


def main():
    os.makedirs(OUT, exist_ok=True)
    # Tables come from the rules files, prose from the manuscript - the split
    # webbook/README.md describes. Every rules file is offered, so a chapter
    # that flattens a table anywhere can find its columns.
    # Scoped per chapter, not pooled. A chapter should only ever be able to
    # pull tables out of the rules file that covers the same subject; letting
    # every file compete invites a match from somewhere unrelated.
    sources = {
        "equipment": ["weapons.md"],
        "gifts":     ["gifts.md"],
        "fate":      ["fate.md"],
        "flaws":     ["flaws.md"],
        "boons":     ["boons.md"],
        "skills":    ["skills.md", "premade-skills.md"],
        "resources": ["resources.md"],
        "how-to-play":          ["rules.md"],
        "creating-a-character": ["character-creation.md"],
        "advancement":          ["costs.md"],
        "glossary":             ["glossary.md"],
        "introduction":         [],
    }
    rules_dir = os.path.join(ROOT, "rules")
    tables_for = {}
    for slug, names in sources.items():
        acc = []
        for name in names:
            path = os.path.join(rules_dir, name)
            if os.path.exists(path):
                acc.extend(rules_tables(path))
        tables_for[slug] = acc
    written = []

    for i, (frag, slug, section, title) in enumerate(CHAPTERS):
        uuid, binder_title = chapter_uuid(frag)
        chunks = to_chunks(uuid)
        chunks = restore_tables(chunks, tables_for.get(slug, []))
        chunks = wrap_entries(chunks)
        if slug == "gifts":
            chunks = wrap_headed_entries(
                chunks, "## The Gift List",
                gift_lists(os.path.join(ROOT, "rules", "gifts.md")))
        prev_slug = CHAPTERS[i - 1][1] if i else None
        next_slug = CHAPTERS[i + 1][1] if i + 1 < len(CHAPTERS) else None

        front = [
            "---",
            "layout: webbook",
            "title: " + yaml_quote(title),
            "chapter: %d" % (i + 1),
            "nav_section: " + section,
        ]
        if prev_slug:
            front.append("prev_url: /webbook/%s.html" % prev_slug)
            front.append("prev_title: " + yaml_quote(CHAPTERS[i - 1][3]))
        if next_slug:
            front.append("next_url: /webbook/%s.html" % next_slug)
            front.append("next_title: " + yaml_quote(CHAPTERS[i + 1][3]))
        front.append("---")

        page = "\n".join(front) + "\n" + BANNER + "\n" + body_of(chunks)
        path = os.path.join(OUT, slug + ".md")
        io.open(path, "w", encoding="utf-8", newline="\n").write(page)
        written.append((binder_title, slug, len(chunks), sum(len(c.split()) for c in chunks)))

    # The contents page.
    lines = [
        "---",
        "layout: webbook",
        'title: "The Player\'s Guide"',
        "nav_section: start",
        "---",
        BANNER.rstrip("\n"),
        "",
        "The whole book, chapter by chapter. This is the same text as the print",
        "edition - the manuscript is the source, and this is generated from it.",
        "",
    ]
    for i, (_frag, slug, _sec, title) in enumerate(CHAPTERS):
        lines.append("%d. [%s](/webbook/%s.html)" % (i + 1, title, slug))
    lines.append("")
    lines.append("Chapter 13, Running the Game, is still being written.")
    lines.append("")
    io.open(os.path.join(OUT, "index.md"), "w", encoding="utf-8", newline="\n").write(
        "\n".join(lines))

    total = sum(w for _, _, _, w in written)
    print("%d chapters -> %s" % (len(written), OUT))
    for t, slug, n, w in written:
        print("  %-34s %-22s %5d chunks %6d words" % (t, slug + ".md", n, w))
    print("  %-57s %6d words total" % ("", total))
    print("  index.md")


if __name__ == "__main__":
    main()
