# -*- coding: utf-8 -*-
"""Pin every Creator module to its own contents, so a browser can never
run a mix of two releases.

GitHub Pages lets a browser reuse any file it fetched in the last ten
minutes. The Creator is a few dozen ES modules that import each other, so
right after a release a browser can pair a new main.js with an old
state.js. When the two disagree the app either stops dead ("does not
provide an export named ...") or, worse, half-works: an Import fails and
the character already on screen stays there looking like the result. That
is how a player's imported Viktor came up with somebody else's Skills.

This writes an import map into each page under app/ that loads modules.
Every module's address carries a fingerprint of its contents
(state.js?v=1a2b3c4d), so a changed file is a new address the browser has
never cached, and an unchanged one keeps its cache. Import maps remap
relative imports too, so no module has to change how it imports.

    python tools/stamp-app-modules.py           # rewrite the maps
    python tools/stamp-app-modules.py --check   # exit 1 if any map is stale

The pre-commit hook runs --check whenever app/ code is staged.

playsheet/ - the Owlbear character sheet - imports the same modules from
../app/, so its page carries a map of those too, keyed by the path it
uses, plus its own module.
"""
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
APP = os.path.join(ROOT, "app")
PLAYSHEET = os.path.join(ROOT, "playsheet")
TRACKER = os.path.join(ROOT, "tracker")

BEGIN = "<!-- module-stamps: generated by tools/stamp-app-modules.py, do not edit -->"
END = "<!-- /module-stamps -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
# A page's own entry module is a src attribute, which import maps do not
# touch, so it carries the stamp directly.
ENTRY = re.compile(r'(<script type="module" src=")([^"?]+\.js)(?:\?v=[0-9a-f]+)?(")')


def fingerprint(path):
    data = io.open(path, "rb").read().replace(b"\r\n", b"\n")
    return hashlib.sha1(data).hexdigest()[:10]


def modules(prefix="./"):
    found = {}
    for dirpath, dirs, files in os.walk(APP):
        dirs[:] = [d for d in dirs if d not in ("icons", "node_modules")]
        for f in files:
            if f.endswith(".js"):
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, APP).replace(os.sep, "/")
                found[prefix + rel] = full
    return dict(sorted(found.items()))


def playsheet_modules():
    mods = modules("../app/")
    for f in os.listdir(PLAYSHEET):
        if f.endswith(".js"):
            mods["./" + f] = os.path.join(PLAYSHEET, f)
    return dict(sorted(mods.items()))


def stamped(page_text, mods):
    imports = {key: "%s?v=%s" % (key, fingerprint(full)) for key, full in mods.items()}
    block = "%s\n<script type=\"importmap\">\n%s\n</script>\n%s" % (
        BEGIN, json.dumps({"imports": imports}, indent=1), END)
    if BLOCK.search(page_text):
        text = BLOCK.sub(lambda m: block, page_text)
    else:
        # Before the first module script: an import map only applies to
        # modules loaded after it.
        i = page_text.index('<script type="module"')
        text = page_text[:i] + block + "\n" + page_text[i:]

    def entry(m):
        key = "./" + m.group(2)
        v = fingerprint(mods[key]) if key in mods else None
        return m.group(1) + m.group(2) + ("?v=" + v if v else "") + m.group(3)
    return ENTRY.sub(entry, text)


def pages():
    mods = modules()
    for f in sorted(os.listdir(APP)):
        if f.endswith(".html"):
            yield f, os.path.join(APP, f), mods
    if os.path.isdir(PLAYSHEET):
        yield "playsheet/index.html", os.path.join(PLAYSHEET, "index.html"), playsheet_modules()
    # The Battle Tracker's module lives inline in its page, so only the
    # Creator modules it imports need stamping.
    if os.path.isdir(TRACKER):
        yield "tracker/index.html", os.path.join(TRACKER, "index.html"), modules("../app/")


def main():
    check = "--check" in sys.argv
    stale = []
    for f, path, mods in pages():
        raw = io.open(path, encoding="utf-8", newline="").read()
        if '<script type="module"' not in raw:
            continue
        nl = "\r\n" if "\r\n" in raw else "\n"
        text = raw.replace("\r\n", "\n")
        new = stamped(text, mods)
        if new != text:
            stale.append(f)
            if not check:
                io.open(path, "w", encoding="utf-8", newline="").write(new.replace("\n", nl))
    if check:
        if stale:
            print("module stamps are stale in: %s" % ", ".join(stale))
            print("run: python tools/stamp-app-modules.py")
            return 1
        print("module stamps current")
        return 0
    print("stamped %d page(s): %s" % (len(stale), ", ".join(stale) or "none changed"))
    return 0


sys.exit(main())
